spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ektrepha_api
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
