spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ektrepha_api
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info